language: ruby

rvm: 2.7.3

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE chitter;'
  - psql --dbname=chitter -U postgres -c 'CREATE TABLE peeps(id SERIAL PRIMARY KEY, content VARCHAR(140));'

script:
  - bundle exec rspec
