language: ruby

rvm: 2.7.3

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE chitter_test;'
  - psql --dbname=chitter_test -U postgres -c 'CREATE TABLE peeps(id SERIAL PRIMARY KEY, content VARCHAR(140));'
  - psql --dbname=chitter_test -U postgres -c 'ALTER TABLE peeps ADD COLUMN timestamp TIMESTAMPTZ;'

script:
  - bundle exec rspec
